/**
 * Report generation — produces a markdown summary of all experiments.
 */
import type { ProgramConfig, MetricSnapshot, ExperimentEntry } from "@/lib/schemas.js";
import { readBaseline, readBest, readHistory } from "@/lib/store.js";

export interface ReportData {
  program: ProgramConfig;
  baseline: MetricSnapshot | null;
  best: MetricSnapshot | null;
  history: ExperimentEntry[];
}

export async function gatherReportData(program: ProgramConfig, cwd: string): Promise<ReportData> {
  const [baseline, best, history] = await Promise.all([
    readBaseline(cwd),
    readBest(cwd),
    readHistory(cwd),
  ]);
  return { program, baseline, best, history };
}

export function formatReport(data: ReportData): string {
  const { program, baseline, best, history } = data;
  const lines: string[] = [];

  // Header
  lines.push("# Experiment Report");
  lines.push("");
  lines.push(`**Objective**: ${program.objective}`);
  lines.push(`**Metric**: ${program.metric.name} (${program.metric.direction.replace(/_/g, " ")})`);
  lines.push(`**Scope**: ${program.scope.join(", ")}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  if (baseline) lines.push(`- **Baseline**: ${baseline.metric}`);
  if (best) lines.push(`- **Best**: ${best.metric}`);
  if (baseline && best) {
    const delta = best.metric - baseline.metric;
    const sign = delta >= 0 ? "+" : "";
    lines.push(`- **Improvement**: ${sign}${delta}`);
  }

  const experiments = history.filter((e) => e.id !== "baseline");
  const kept = experiments.filter((e) => e.status === "kept");
  const reverted = experiments.filter((e) => e.status === "reverted");
  const crashed = experiments.filter((e) => e.status === "crash" || e.status === "timeout");
  const rate = experiments.length > 0 ? Math.round((kept.length / experiments.length) * 100) : 0;

  lines.push(
    `- **Experiments**: ${experiments.length} total (${kept.length} kept, ${reverted.length} reverted, ${crashed.length} crashed)`,
  );
  lines.push(`- **Success rate**: ${rate}%`);
  lines.push("");

  // Top improvements
  if (kept.length > 0) {
    const sorted = [...kept].sort((a, b) => {
      const da = a.delta ?? 0;
      const db = b.delta ?? 0;
      return program.metric.direction === "lower_is_better" ? da - db : db - da;
    });
    const top = sorted.slice(0, 5);

    lines.push("## Top Improvements");
    lines.push("");
    lines.push("| # | Title | Metric | Delta | Commit |");
    lines.push("|---|-------|--------|-------|--------|");
    for (let i = 0; i < top.length; i++) {
      const e = top[i];
      const delta = e.delta !== null ? (e.delta >= 0 ? `+${e.delta}` : `${e.delta}`) : "-";
      lines.push(
        `| ${i + 1} | ${e.title} | ${e.resultMetric ?? "-"} | ${delta} | ${e.commitSha ?? "-"} |`,
      );
    }
    lines.push("");
  }

  // Full history
  if (experiments.length > 0) {
    lines.push("## Experiment History");
    lines.push("");
    lines.push("| # | Title | Status | Metric | Delta | Duration |");
    lines.push("|---|-------|--------|--------|-------|----------|");
    for (let i = 0; i < experiments.length; i++) {
      const e = experiments[i];
      const delta = e.delta !== null ? (e.delta >= 0 ? `+${e.delta}` : `${e.delta}`) : "-";
      const metric = e.resultMetric !== null ? String(e.resultMetric) : "-";
      lines.push(
        `| ${i + 1} | ${e.title} | ${e.status} | ${metric} | ${delta} | ${e.durationSeconds}s |`,
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by auto-evolve*`);
  lines.push("");

  return lines.join("\n");
}
